# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kbom < Formula
  desc "The Kubernetes Bill of Materials (KBOM) standard provides insight into container orchestration tools widely used across the industry."
  homepage "https://github.com/rad-security/kbom"
  version "0.3.0"
  license "Apache 2"

  on_macos do
    on_intel do
      url "https://github.com/rad-security/kbom/releases/download/v0.3.0/kbom_0.3.0_darwin_amd64.tar.gz"
      sha256 "5b8953fff59eb70657f48de64df41d433c31405b658bd9bff72607d59d30e602"

      def install
        bin.install "kbom"
      end
    end
    on_arm do
      url "https://github.com/rad-security/kbom/releases/download/v0.3.0/kbom_0.3.0_darwin_arm64.tar.gz"
      sha256 "05348149bb064c3c0ab998321c108cfcaf5ea5dff677adf264b45e15fb4c5d74"

      def install
        bin.install "kbom"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/rad-security/kbom/releases/download/v0.3.0/kbom_0.3.0_linux_amd64.tar.gz"
        sha256 "fcee1f7f3b13bddc37f85db10d7408bef51853966e17d1ff7a0b0bed4d3f3ecf"

        def install
          bin.install "kbom"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/rad-security/kbom/releases/download/v0.3.0/kbom_0.3.0_linux_arm64.tar.gz"
        sha256 "d53623c6c4d4691ccc3354e278478bcf82e2a87445014b3e03e1411183b75cf5"

        def install
          bin.install "kbom"
        end
      end
    end
  end

  test do
    system "#{bin}/kbom", "version"
  end
end
