# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kbom < Formula
  desc "The Kubernetes Bill of Materials (KBOM) standard provides insight into container orchestration tools widely used across the industry."
  homepage "https://github.com/rad-security/kbom"
  version "0.2.6"
  license "Apache 2"

  on_macos do
    on_intel do
      url "https://github.com/rad-security/kbom/releases/download/v0.2.6/kbom_0.2.6_darwin_amd64.tar.gz"
      sha256 "5a9fd07a8dfee7a9a4b47fd6339f6797e9315512dd0ae1c855eb57a315415d73"

      def install
        bin.install "kbom"
      end
    end
    on_arm do
      url "https://github.com/rad-security/kbom/releases/download/v0.2.6/kbom_0.2.6_darwin_arm64.tar.gz"
      sha256 "606f6035af774471197fc662ef0dc5d75f0f7b377106389d054b2869682fced7"

      def install
        bin.install "kbom"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/rad-security/kbom/releases/download/v0.2.6/kbom_0.2.6_linux_amd64.tar.gz"
        sha256 "737b1e215188557cae68eb1371f3fabc268fb60374586e77b979fb2d75fe5749"

        def install
          bin.install "kbom"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/rad-security/kbom/releases/download/v0.2.6/kbom_0.2.6_linux_arm64.tar.gz"
        sha256 "e84dffac758902474cd2e22589111843b00367026b435b90304168c2844d9015"

        def install
          bin.install "kbom"
        end
      end
    end
  end

  test do
    system "#{bin}/kbom", "version"
  end
end
